const build='2026-07-04-CR-016-STABLE';
const stamp=Date.now();
let state={},managed={},artifacts=[],capmap={capabilities:[]},versions={applications:[]},cicd={environments:[]},tab='control',selected=0,appScope='ALL';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=x=>Object.values(x||{}).join(' ').toLowerCase();
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function bucket(t){t=String(t||'').toLowerCase();if(/stuck|blocked|fail|rejected|not approved|not implemented|missing|rollback|no go|stop/.test(t))return 'stuck';if(/pending|review|planned|deferred|in progress|candidate|not active|partial|warning/.test(t))return 'open';if(/pass|solved|closed|complete|verified|validated|confirmed|active|canonical|baseline|ready/.test(t))return 'done';return 'other'}
function chip(b,l){const i={done:'✅',open:'⚠️',stuck:'⛔',other:'ℹ️'}[b]||'ℹ️';const t=l||{done:'PASS / Done',open:'Warning / Review',stuck:'Blocked / Stop',other:'Info / N/A'}[b]||'Info / N/A';return `<span class='chip ${b}'>${i} ${esc(t)}</span>`}
function capBucket(c){const r=parseInt(String(c.readiness||'0').replace('%',''),10)||0;return r>=75?'done':r>=40?'open':'stuck'}
function work(){return managed.register_rows||[]}
function classify(r){return bucket(`${r.lifecycle} ${r.state}`)}
function parseArtifacts(md){return md.split('\n').filter(l=>l.startsWith('| ')&&!l.includes('---')&&!l.includes('Artifact ID')).map(l=>{const p=l.split('|').slice(1,-1).map(x=>x.trim().replaceAll('`',''));return {id:p[0],name:p[1],location:p[2],status:p[3],domain:p[4],initiative:p[5]}}).filter(x=>x.id)}
const byId=(arr,id)=>(arr||[]).find(x=>String(x.id||'')===id);
const match=(items,terms)=>(items||[]).filter(x=>(terms||[]).some(t=>text(x).includes(String(t).toLowerCase())));
function findings(){return [...(managed.not_full_backlog_warning||[]).map((r,i)=>({id:`FIND-WARN-${i+1}`,title:r.warning,category:'Finding / Warning',lifecycle:'Finding',state:r.dashboard_effect||'',source:r.repo_basis||'managed-work.json'})),...(managed.why_task_count_looked_small||[]).map((r,i)=>({id:`FIND-CAUSE-${i+1}`,title:r.reason,category:'Finding / Cause',lifecycle:'Finding',state:r.meaning||'',source:'managed-work.json'})),...(managed.next_dashboard_improvements||[]).map(r=>({id:r.id,title:r.label,category:'Finding / Improvement Candidate',lifecycle:'Future Improvement',state:r.status,source:'managed-work.json'}))]}
function appOfName(name,layer=''){const s=(name+' '+layer).toLowerCase();if(/pool|chemical|measurement|alert|maintenance/.test(s))return 'RANI_POOL';if(/trading|trade|broker|market|visual context|decision|execution engine|data ingestion|system logs|research|model evolution/.test(s))return 'RANI_TRADING';return 'RANI_OS'}
function appOfCap(c){return c.application||appOfName(c.name||c.capability,c.layer)}
function appOfWork(r){const s=text(r);if(/pool|chemical|measurement|maintenance/.test(s))return 'RANI_POOL';if(/trading|trade|broker|market|ibkr|verdict|execution|evidence/.test(s))return 'RANI_TRADING';return 'RANI_OS'}
function appOfArtifact(a){const s=text(a);if(/pool|chemical|maintenance/.test(s))return 'RANI_POOL';if(/trading|trade|broker|market|visual|pine|gpt_decision|gpt_brain|execution/.test(s))return 'RANI_TRADING';return 'RANI_OS'}
function inScope(a){return appScope==='ALL'||a===appScope}
function capabilityUniverse(){const roadmap=(state.capabilities||[]).map(c=>({name:c.capability,source:'Capability Roadmap',readiness:c.readiness,status:c.status,layer:c.layer,priority:c.priority,next:c.next}));const mapped=(capmap.capabilities||[]).map(c=>({name:c.name,source:'Explicit Capability Map',readiness:c.readiness,status:c.status,layer:c.layer,priority:c.priority,next:c.next_safe_action,capability_id:c.capability_id,application:appOfCap(c)}));const pool=[{name:'POOL_CONTROLLER Framework',source:'Application Boundary',readiness:'0%',status:'Framework / Not Implemented',layer:'Application / Pool',priority:'P3',next:'Do not implement until owner approves',capability_id:'CAP-POOL-FRAMEWORK',application:'RANI_POOL'}];const m=new Map();[...roadmap,...mapped,...pool].forEach(c=>{const k=norm(c.name);m.set(k,{...(m.get(k)||{}),...c,application:c.application||appOfName(c.name,c.layer)})});return [...m.values()]}
function model(){return (capmap.capabilities||[]).map((c,i)=>{const known=(c.known_work_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const blockers=(c.blocking_bug_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const cand=(c.candidate_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const arts=match(artifacts,c.artifact_queries||[]);const finds=match(findings(),c.finding_queries||[]);const app=appOfCap(c);const gates=c.owner_gates||[];return {i,c:{...c,application:app},known,blockers,cand,arts,finds,missing:c.missing_work||[],check:c.completion_checklist||[],gates}}).filter(x=>inScope(x.c.application))}
function table(rows,cols){return `<div class='note table-count'>Records in this table: ${(rows||[]).length}</div><div class='tablewrap'><table><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${(rows||[]).map(r=>`<tr>${cols.map(c=>`<td>${r[c[1]]??''}</td>`).join('')}</tr>`).join('')||`<tr><td colspan='${cols.length}' class='bad'>No matching rows</td></tr>`}</tbody></table></div>`}
function capTable(items){return table((items||[]).map(x=>({App:esc(x.c.application),Status:chip(capBucket(x.c),x.c.readiness||x.c.status),Priority:esc(x.c.priority),Capability:esc(x.c.name),Confidence:esc(x.c.mapping_confidence||''),Blockers:String(x.blockers.length),Gates:String(x.gates.length),Missing:String(x.missing.length),Next:esc(x.c.next_safe_action||x.c.next||'')})),[['App','App'],['Status','Status'],['Priority','Priority'],['Capability','Capability'],['Confidence','Confidence'],['Blockers','Blockers'],['Gates','Gates'],['Missing','Missing'],['Next','Next']])}
function workTable(rows){return table((rows||[]).filter(r=>inScope(appOfWork(r))).map(r=>({App:esc(appOfWork(r)),State:chip(classify(r),classify(r)),ID:esc(r.id),Title:esc(r.title),Category:esc(r.category),Status:esc(r.state)})),[['App','App'],['State','State'],['ID','ID'],['Title','Title'],['Category','Category'],['Status','Status']])}
function artifactTable(rows){return table((rows||[]).filter(a=>inScope(appOfArtifact(a))).map(a=>({App:esc(appOfArtifact(a)),State:chip(bucket(a.status),bucket(a.status)),ID:esc(a.id),Name:esc(a.name),Status:esc(a.status),Domain:esc(a.domain)})),[['App','App'],['State','State'],['ID','ID'],['Name','Name'],['Status','Status'],['Domain','Domain']])}
function css(){document.head.innerHTML=`<meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>RANI OS Admin</title><style>:root{--bg:#07111f;--card:#0d1b2e;--card2:#11243a;--text:#e8eef7;--muted:#9fb0c7;--border:#223855;--blue:#60a5fa;--green:#36d399;--yellow:#fbbf24;--red:#fb7185;--gray:#94a3b8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,sans-serif;line-height:1.4}header{padding:14px;background:#08162a;border-bottom:1px solid var(--border)}h1{margin:0 0 4px;font-size:22px}.sub,.note{color:var(--muted);font-size:13px}.tabs,.counters,.cards,.kpis,.apps{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px;margin-top:10px}.tabs button,.counter,.card,.kpi,.appbtn{padding:10px;border:1px solid var(--border);border-radius:12px;background:var(--card2);color:var(--text);cursor:pointer;text-align:left}.tabs button.active,.card.active,.appbtn.active{background:var(--blue);color:#07111f;font-weight:bold}.num{font-size:21px;font-weight:700;color:var(--blue);direction:ltr}.label,.txt{font-size:12px;color:var(--muted)}main{padding:14px;display:grid;gap:12px}section,.panel,.mini{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:14px;overflow:hidden}.tablewrap{overflow-x:hidden;border:1px solid var(--border);border-radius:12px;margin-top:8px}table{width:100%;border-collapse:collapse;direction:ltr;text-align:left;table-layout:fixed}th,td{padding:8px;border-bottom:1px solid rgba(255,255,255,.08);vertical-align:top;overflow-wrap:anywhere;word-break:break-word}th{color:var(--muted);font-weight:normal;background:#0b1a2d}.chip{display:inline-block;padding:4px 7px;border-radius:999px;font-size:11px}.chip.done{background:rgba(54,211,153,.18);color:var(--green);border:1px solid rgba(54,211,153,.5)}.chip.open{background:rgba(251,191,36,.18);color:var(--yellow);border:1px solid rgba(251,191,36,.5)}.chip.stuck{background:rgba(251,113,133,.18);color:var(--red);border:1px solid rgba(251,113,133,.5)}.chip.other{background:rgba(148,163,184,.18);color:var(--gray);border:1px solid rgba(148,163,184,.5)}.table-count{font-weight:600;color:var(--text)}.bad{color:var(--red)}.legend{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.mini{margin-top:12px;background:rgba(255,255,255,.02)}@media(max-width:820px){header{padding:10px}h1{font-size:18px}.tabs,.counters,.cards,.kpis,.apps{grid-template-columns:1fr 1fr}main{padding:8px}section,.panel,.mini{padding:10px}table{font-size:11px}th,td{padding:6px 4px}}`}
function appSwitch(){const u=capabilityUniverse();const counts={RANI_OS:u.filter(c=>c.application==='RANI_OS').length,RANI_TRADING:u.filter(c=>c.application==='RANI_TRADING').length,RANI_POOL:u.filter(c=>c.application==='RANI_POOL').length};return `<div class='apps'><button class='appbtn ${appScope==='ALL'?'active':''}' data-app='ALL'>🌐 ALL</button><button class='appbtn ${appScope==='RANI_OS'?'active':''}' data-app='RANI_OS'>🧠 RANI_OS (${counts.RANI_OS})</button><button class='appbtn ${appScope==='RANI_TRADING'?'active':''}' data-app='RANI_TRADING'>📈 RANI_TRADING (${counts.RANI_TRADING})</button><button class='appbtn ${appScope==='RANI_POOL'?'active':''}' data-app='RANI_POOL'>🏊 RANI_POOL (${counts.RANI_POOL})</button></div>`}
function counters(){const all=capabilityUniverse().filter(c=>inScope(c.application)),mapped=model(),unmapped=all.length-mapped.length;const items=[['control',`${mapped.length}/${all.length}`,'Mapped / Total'],['unmapped',unmapped,'Unmapped'],['owner',mapped.reduce((n,x)=>n+x.gates.length,0),'Owner Gates'],['work',work().filter(r=>inScope(appOfWork(r))).length,'Work Records'],['artifacts',artifacts.filter(a=>inScope(appOfArtifact(a))).length,'Artifacts']];return `<div class='counters'>${items.map(([a,n,l])=>`<button class='counter' data-nav='${a}'><div class='num'>${esc(n)}</div><div class='label'>${esc(l)}</div></button>`).join('')}</div>`}
function layout(content){document.body.innerHTML=`<header><h1>RANI OS Admin</h1><div class='sub'>Build ${build} · Clean single-file stable build · Safe App Scope + Visual Status</div>${appSwitch()}<div class='tabs'><button data-tab='control'>Control Room</button><button data-tab='mapping'>Mapping Coverage</button><button data-tab='priority'>Priority Board</button><button data-tab='capmap'>Capability Map</button><button data-tab='unmapped'>Unmapped</button><button data-tab='owner'>Owner Gates</button><button data-tab='work'>Work Records</button><button data-tab='artifacts'>Artifacts</button><button data-tab='versions'>Version Center</button><button data-tab='cicd'>CI/CD</button><button data-tab='reports'>Reports</button></div>${counters()}<div class='legend'>${chip('done','PASS / Done')} ${chip('open','Warning / Review')} ${chip('stuck','Blocked / Stop')} ${chip('other','Info / N/A')}</div></header><main>${content}</main>`;wire()}
function control(){const all=capabilityUniverse().filter(c=>inScope(c.application)),mapped=model(),unmapped=all.length-mapped.length;return `<section><h2>Control Room</h2><div class='note'>Stable restored build. App scope is separated and visual status is active. Capability Funnel is parked until a safer implementation is ready.</div><div class='kpis'><div class='kpi'><div class='num'>${mapped.length}/${all.length}</div><div>Mapped / Total</div></div><div class='kpi'><div class='num'>${unmapped}</div><div>Unmapped</div></div><div class='kpi'><div class='num'>${mapped.reduce((n,x)=>n+x.gates.length,0)}</div><div>Owner Gates</div></div><div class='kpi'><div class='num'>${build}</div><div>Build</div></div></div>${table([{K:'Source of Truth',V:(state.system_status||{}).source_of_truth},{K:'Projection Status',V:(state.system_status||{}).projection_status},{K:'Active Work',V:(state.current_work_item||{}).active_work_item},{K:'Scope',V:appScope}], [['Context','K'],['Value','V']])}</section>`}

function health(h){h=String(h||'').toLowerCase();return h==='green'?chip('done','PASS / Done'):h==='yellow'?chip('open','Warning / Review'):h==='red'?chip('stuck','Blocked / Stop'):chip('other','Info / N/A')}
function titleCase(s){return String(s||'').split('-').map(w=>w?w[0].toUpperCase()+w.slice(1):w).join('-')}
function mapping(){const all=capabilityUniverse().filter(c=>inScope(c.application)),mapped=model(),mappedNames=new Set(mapped.map(x=>norm(x.c.name)));const done=mapped.filter(x=>capBucket(x.c)==='done').length,review=mapped.filter(x=>capBucket(x.c)==='open').length,blocked=mapped.filter(x=>capBucket(x.c)==='stuck').length;return `<section><h2>Mapping Coverage</h2><div class='note'>Plain coverage view for the selected app scope.</div><div class='kpis'><div class='kpi'><div class='num'>${mapped.length}/${all.length}</div><div>Mapped capabilities</div></div><div class='kpi'><div class='num'>${all.length-mapped.length}</div><div>Unmapped capabilities</div></div><div class='kpi'><div class='num'>${done}</div><div>PASS / Done</div></div><div class='kpi'><div class='num'>${review}</div><div>Warning / Review</div></div><div class='kpi'><div class='num'>${blocked}</div><div>Blocked / Stop</div></div></div>${table(all.map(c=>({App:esc(c.application),Coverage:mappedNames.has(norm(c.name))?chip('done','PASS / Done'):chip('open','Warning / Review'),Capability:esc(c.name),Readiness:esc(c.readiness||''),Status:esc(c.status||''),Next:esc(c.next_safe_action||c.next||'')})),[['App','App'],['Coverage','Coverage'],['Capability','Capability'],['Readiness','Readiness'],['Status','Status'],['Next','Next']])}</section>`}
function versionCenter(){const rows=(versions.applications||[]).filter(v=>inScope(v.app)||v.app==='ADMIN_WEB').map(v=>({App:esc(v.app),Current:esc(v.current_stable),Latest:esc(v.latest_build),Status:esc(v.status),Health:health(v.health),Meaning:esc(v.plain_language),Failed:esc(v.last_failed_version),Rollback:esc(v.rollback_reason),Gate:esc(v.owner_gate),Next:esc(v.next_candidate)}));return `<section><h2>Version Center</h2><div class='note'>Source: version-center.json. This explains version state in plain language per app.</div>${table(rows,[['App','App'],['Current Stable','Current'],['Latest Build','Latest'],['Status','Status'],['Health','Health'],['Plain Language Meaning','Meaning'],['Last Failed Version','Failed'],['Rollback Reason','Rollback'],['Owner Gate','Gate'],['Next Candidate','Next']])}</section>`}
function cicdView(){const rows=(cicd.environments||[]).map(e=>({Environment:esc(titleCase(e.name)),Status:esc(e.status),Health:health(e.health),Purpose:esc(e.purpose),Promotion:esc(e.promotion_rule),Rollback:esc(e.rollback_rule),Gap:esc(cicd.current_gap),Next:esc(cicd.next_safe_action)}));return `<section><h2>CI/CD View</h2><div class='note'>Pipeline: ${esc(cicd.required_pipeline||'Build -> Dev -> Test -> Pre-Prod -> Owner PASS -> Production')}</div>${table(rows,[['Development / Testing / Pre-Prod / Production','Environment'],['Status','Status'],['Health','Health'],['Purpose','Purpose'],['Promotion rules','Promotion'],['Rollback rules','Rollback'],['Current gap','Gap'],['Next safe action','Next']])}</section>`}

function priority(){return `<section><h2>Priority Board</h2>${capTable(model())}</section>`}
function capmapView(){return `<section><h2>Capability Map</h2>${capTable(model())}</section>`}
function unmapped(){const keys=new Set((capmap.capabilities||[]).map(c=>norm(c.name)));const rows=capabilityUniverse().filter(c=>!keys.has(norm(c.name))&&inScope(c.application)).map(c=>({c:{...c,mapping_confidence:'Unmapped',next_safe_action:'Create capability-map entry'},known:[],blockers:[],cand:[],arts:[],finds:[],missing:['Create capability_id'],check:[],gates:[]}));return `<section><h2>Unmapped Capabilities</h2>${capTable(rows)}</section>`}
function owner(){let rows=[];model().forEach(x=>x.gates.forEach(g=>rows.push({App:esc(x.c.application),Cap:esc(x.c.name),Gate:esc(g),Status:chip('open','Owner Gate'),Next:esc(x.c.next_safe_action)})));return `<section><h2>Owner Gates</h2>${table(rows,[['App','App'],['Capability','Cap'],['Gate','Gate'],['Status','Status'],['Next','Next']])}</section>`}
function workView(){return `<section><h2>Work Records</h2>${workTable(work())}</section>`}
function artView(){return `<section><h2>Artifacts</h2>${artifactTable(artifacts)}</section>`}
function reports(){return `<section><h2>Reports</h2>${capTable(model())}</section>`}
function view(){return tab==='mapping'?mapping():tab==='priority'?priority():tab==='capmap'?capmapView():tab==='unmapped'?unmapped():tab==='owner'?owner():tab==='work'?workView():tab==='artifacts'?artView():tab==='versions'?versionCenter():tab==='cicd'?cicdView():tab==='reports'?reports():control()}
function render(){layout(view())}
function wire(){document.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>{appScope=b.dataset.app;render()});document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.onclick=()=>{tab=b.dataset.tab;render()}});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{tab=b.dataset.nav==='work'?'work':b.dataset.nav==='artifacts'?'artifacts':b.dataset.nav==='owner'?'owner':b.dataset.nav==='unmapped'?'unmapped':'control';render()})}
async function boot(){css();const [st,mw,md,cm,vc,cd]=await Promise.all([fetch('state.json?b=cr016-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('managed-work.json?b=cr016-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('artifact-register-public.md?b=cr016-'+stamp,{cache:'no-store'}).then(r=>r.text()),fetch('capability-map.json?b=cr016-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('version-center.json?b=cr016-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('cicd-environments.json?b=cr016-'+stamp,{cache:'no-store'}).then(r=>r.json())]);state=st;managed=mw;artifacts=parseArtifacts(md);capmap=cm;versions=vc;cicd=cd;render()}
boot().catch(()=>{document.body.innerHTML='<section><div class="bad">Could not load safe dashboard data</div></section>'});
