const build='2026-07-04-CR-015';
const stamp=Date.now();
let state={},managed={},artifacts=[],capmap={capabilities:[]},tab='control',selected=0,appScope='ALL',funnelStage='total',workFilter={q:'',view:'all'},artFilter={q:'',view:'all'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=x=>Object.values(x||{}).join(' ').toLowerCase();
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function bucket(t){t=String(t||'').toLowerCase();if(/stuck|blocked|fail|rejected|not approved|not implemented|missing|rollback|no go|stop/.test(t))return 'stuck';if(/pending|review|planned|deferred|in progress|candidate|not active|partial|warning/.test(t))return 'open';if(/pass|solved|closed|complete|verified|validated|confirmed|active|canonical|baseline|ready/.test(t))return 'done';return 'other'}
function chip(b,label){const icon={done:'✅',open:'⚠️',stuck:'⛔',other:'ℹ️'}[b]||'ℹ️';return `<span class='chip ${b}'>${icon} ${esc(label||b)}</span>`}
function capBucket(c){const r=parseInt(String(c.readiness||'0').replace('%',''),10)||0;return r>=75?'done':r>=40?'open':'stuck'}
function pct(d,t){return t?`${Math.round(d*100/t)}%`:'0%'}
function work(){return managed.register_rows||[]}
function classify(r){return bucket(`${r.lifecycle} ${r.state}`)}
function metric(rows=work()){let done=0,open=0,stuck=0,other=0;rows.forEach(r=>{const b=classify(r);if(b==='done')done++;else if(b==='open')open++;else if(b==='stuck')stuck++;else other++});return {done,open,stuck,other,total:rows.length}}
function parseArtifacts(md){return md.split('\n').filter(l=>l.startsWith('| ')&&!l.includes('---')&&!l.includes('Artifact ID')).map(l=>{const p=l.split('|').slice(1,-1).map(x=>x.trim().replaceAll('`',''));return {id:p[0],name:p[1],location:p[2],status:p[3],domain:p[4],initiative:p[5]}}).filter(x=>x.id)}
const byId=(arr,id)=>(arr||[]).find(x=>String(x.id||'')===id);
const match=(items,terms)=>(items||[]).filter(x=>(terms||[]).some(t=>text(x).includes(String(t).toLowerCase())));
const bugs=()=>work().filter(r=>String(r.id||'').startsWith('BUG-'));
const opsbugs=()=>work().filter(r=>String(r.id||'').startsWith('OPS-BUG'));
const ideas=()=>work().filter(r=>String(r.id||'').startsWith('CAND-')||String(r.category||'').toLowerCase().includes('idea'));
function findings(){return [...(managed.not_full_backlog_warning||[]).map((r,i)=>({id:`FIND-WARN-${i+1}`,title:r.warning,category:'Finding / Warning',lifecycle:'Finding',state:r.dashboard_effect||'',source:r.repo_basis||'managed-work.json'})),...(managed.why_task_count_looked_small||[]).map((r,i)=>({id:`FIND-CAUSE-${i+1}`,title:r.reason,category:'Finding / Cause',lifecycle:'Finding',state:r.meaning||'',source:'managed-work.json'})),...(managed.next_dashboard_improvements||[]).map(r=>({id:r.id,title:r.label,category:'Finding / Improvement Candidate',lifecycle:'Future Improvement',state:r.status,source:'managed-work.json'}))]}
function appOfName(name,layer=''){const s=(name+' '+layer).toLowerCase();if(/pool|chemical|measurement|alert|maintenance/.test(s))return 'RANI_POOL';if(/trading|trade|broker|market|visual context|decision|execution engine|data ingestion|system logs|research|model evolution/.test(s))return 'RANI_TRADING';return 'RANI_OS'}
function appOfCap(c){return c.application||appOfName(c.name||c.capability,c.layer)}
function appOfWork(r){const s=text(r);if(/pool|chemical|measurement|maintenance/.test(s))return 'RANI_POOL';if(/trading|trade|broker|market|ibkr|verdict|execution|evidence/.test(s))return 'RANI_TRADING';return 'RANI_OS'}
function appOfArtifact(a){const s=text(a);if(/pool|chemical|maintenance/.test(s))return 'RANI_POOL';if(/trading|trade|broker|market|visual|pine|gpt_decision|gpt_brain|execution/.test(s))return 'RANI_TRADING';return 'RANI_OS'}
function inScopeApp(app){return appScope==='ALL'||app===appScope}
function capabilityUniverse(){const roadmap=(state.capabilities||[]).map(c=>({name:c.capability,source:'Capability Roadmap',readiness:c.readiness,status:c.status,layer:c.layer,priority:c.priority,next:c.next}));const mapped=(capmap.capabilities||[]).map(c=>({name:c.name,source:'Explicit Capability Map',readiness:c.readiness,status:c.status,layer:c.layer,priority:c.priority,next:c.next_safe_action,capability_id:c.capability_id,application:appOfCap(c)}));const pool=[{name:'POOL_CONTROLLER Framework',source:'Application Boundary',readiness:'0%',status:'Framework / Not Implemented',layer:'Application / Pool',priority:'P3',next:'Do not implement until owner approves',capability_id:'CAP-POOL-FRAMEWORK',application:'RANI_POOL'}];const map=new Map();[...roadmap,...mapped,...pool].forEach(c=>{const k=norm(c.name);if(!map.has(k))map.set(k,{...c,application:c.application||appOfName(c.name,c.layer)});else map.set(k,{...map.get(k),...c,source:'Roadmap + Explicit Map',application:c.application||map.get(k).application})});return [...map.values()]}
function capModel(){return (capmap.capabilities||[]).map((c,i)=>{const known=(c.known_work_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const blockers=(c.blocking_bug_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const cand=(c.candidate_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const arts=match(artifacts,c.artifact_queries||[]);const finds=match(findings(),c.finding_queries||[]);const gates=c.owner_gates||[];const app=appOfCap(c);const score=(c.priority==='P0'?0:c.priority==='P1'?1:2)+(blockers.length?0:1)+(gates.length?0:1)+(c.mapping_confidence==='High'?0:1);return {i,c:{...c,application:app},known,blockers,cand,arts,finds,missing:c.missing_work||[],check:c.completion_checklist||[],gates,score}}).filter(x=>inScopeApp(x.c.application)).sort((a,b)=>a.score-b.score)}
function mappedKeys(){return new Set((capmap.capabilities||[]).map(c=>norm(c.name)))}
function unmappedCaps(){const keys=mappedKeys();return capabilityUniverse().filter(c=>!keys.has(norm(c.name))&&inScopeApp(c.application||appOfName(c.name,c.layer)))}
function allCaps(){const mapped=capModel();const mappedNames=new Set(mapped.map(x=>norm(x.c.name)));const unmapped=unmappedCaps().map((c,i)=>({i:1000+i,c:{...c,application:c.application||appOfName(c.name,c.layer),mapping_confidence:'Unmapped',next_safe_action:'Create capability-map entry'},known:[],blockers:[],cand:[],arts:[],finds:[],missing:['Create capability_id','Create completion checklist','Connect work records','Connect artifacts'],check:[],gates:[],score:9}));return [...mapped,...unmapped]}
function funnelData(){const total=allCaps();const mapped=capModel();const managed=mapped.filter(x=>x.known.length||x.arts.length||x.finds.length||x.cand.length||x.blockers.length);const executable=mapped.filter(x=>!!x.c.next_safe_action&&!x.blockers.length);const validated=mapped.filter(x=>capBucket(x.c)==='done'||String(x.c.status||'').toLowerCase().includes('pass')||String(x.c.status||'').toLowerCase().includes('validated'));const approved=mapped.filter(x=>!x.gates.length&&capBucket(x.c)==='done');const blocked=mapped.filter(x=>x.blockers.length);const owner=mapped.filter(x=>x.gates.length);const missing=mapped.filter(x=>x.missing.length);const lowconf=mapped.filter(x=>['Low','Medium','Unmapped'].includes(String(x.c.mapping_confidence||'')));return {total,mapped,managed,executable,validated,approved,blocked,owner,missing,lowconf}}
function stageItems(stage=funnelStage){const f=funnelData();return f[stage]||f.total}
function stageStatus(stage,count,total){if(stage==='total')return 'other';if(stage==='blocked')return count?'stuck':'done';if(stage==='owner'||stage==='missing'||stage==='lowconf')return count?'open':'done';if(!total)return 'other';const p=count/total;return p>=0.9?'done':p>=0.5?'open':'stuck'}
function table(rows,cols){return `<div class='note table-count'>Records in this table: ${(rows||[]).length}</div><div class='tablewrap'><table><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${(rows||[]).map(r=>`<tr>${cols.map(c=>`<td>${r[c[1]]??''}</td>`).join('')}</tr>`).join('')||`<tr><td colspan='${cols.length}' class='bad'>No matching rows</td></tr>`}</tbody></table></div>`}
function capTable(items){return table((items||[]).map(x=>({App:esc(x.c.application),Status:chip(capBucket(x.c),x.c.readiness||x.c.status),Priority:esc(x.c.priority),Capability:esc(x.c.name),Confidence:esc(x.c.mapping_confidence||''),Blockers:String(x.blockers.length),Gates:String(x.gates.length),Missing:String(x.missing.length),Next:esc(x.c.next_safe_action||x.c.next||'')})),[['App','App'],['Status','Status'],['Priority','Priority'],['Capability','Capability'],['Confidence','Confidence'],['Blockers','Blockers'],['Gates','Gates'],['Missing','Missing'],['Next','Next']])}
function workTable(rows){return table((rows||[]).filter(r=>inScopeApp(appOfWork(r))).map(r=>({App:esc(appOfWork(r)),State:chip(classify(r),classify(r)),ID:esc(r.id),Title:esc(r.title),Category:esc(r.category),Status:esc(r.state)})),[['App','App'],['State','State'],['ID','ID'],['Title','Title'],['Category','Category'],['Status','Status']])}
function artifactTable(rows){return table((rows||[]).filter(a=>inScopeApp(appOfArtifact(a))).map(a=>({App:esc(appOfArtifact(a)),State:chip(bucket(a.status),bucket(a.status)),ID:esc(a.id),Name:esc(a.name),Status:esc(a.status),Domain:esc(a.domain)})),[['App','App'],['State','State'],['ID','ID'],['Name','Name'],['Status','Status'],['Domain','Domain']])}
function listTable(items){return table((items||[]).map((x,i)=>({N:i+1,Item:esc(x)})),[['#','N'],['Item','Item']])}
function css(){document.head.innerHTML=`<meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>RANI OS Admin</title><style>:root{--bg:#07111f;--card:#0d1b2e;--card2:#11243a;--text:#e8eef7;--muted:#9fb0c7;--border:#223855;--blue:#60a5fa;--green:#36d399;--yellow:#fbbf24;--red:#fb7185;--gray:#94a3b8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,sans-serif;line-height:1.4}header{padding:14px;background:#08162a;border-bottom:1px solid var(--border)}h1{margin:0 0 4px;font-size:22px}.sub,.note{color:var(--muted);font-size:13px}.tabs,.counters,.cards,.kpis,.apps,.funnel{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px;margin-top:10px}.tabs button,.counter,.card,.kpi,.appbtn,.fstage{padding:10px;border:1px solid var(--border);border-radius:12px;background:var(--card2);color:var(--text);cursor:pointer;text-align:left}.tabs button.active,.card.active,.appbtn.active,.fstage.active{background:var(--blue);color:#07111f;font-weight:bold}.num{font-size:21px;font-weight:700;color:var(--blue);direction:ltr}.label,.txt{font-size:12px;color:var(--muted)}main{padding:14px;display:grid;gap:12px}section,.panel,.mini{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:14px;overflow:hidden}.tablewrap{overflow-x:hidden;border:1px solid var(--border);border-radius:12px;margin-top:8px}table{width:100%;border-collapse:collapse;direction:ltr;text-align:left;table-layout:fixed}th,td{padding:8px;border-bottom:1px solid rgba(255,255,255,.08);vertical-align:top;overflow-wrap:anywhere;word-break:break-word}th{color:var(--muted);font-weight:normal;background:#0b1a2d}.chip{display:inline-block;padding:4px 7px;border-radius:999px;font-size:11px}.chip.done{background:rgba(54,211,153,.18);color:var(--green);border:1px solid rgba(54,211,153,.5)}.chip.open{background:rgba(251,191,36,.18);color:var(--yellow);border:1px solid rgba(251,191,36,.5)}.chip.stuck{background:rgba(251,113,133,.18);color:var(--red);border:1px solid rgba(251,113,133,.5)}.chip.other{background:rgba(148,163,184,.18);color:var(--gray);border:1px solid rgba(148,163,184,.5)}.table-count{font-weight:600;color:var(--text)}.bad{color:var(--red)}.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:8px;margin:8px 0}.filters input,.filters select{width:100%;padding:10px;border-radius:10px;border:1px solid var(--border);background:var(--card2);color:var(--text)}.legend{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.mini{margin-top:12px;background:rgba(255,255,255,.02)}@media(max-width:820px){header{padding:10px}h1{font-size:18px}.tabs,.counters,.cards,.kpis,.apps,.funnel{grid-template-columns:1fr 1fr}main{padding:8px}section,.panel,.mini{padding:10px}table{font-size:11px}th,td{padding:6px 4px}}`}
function appSwitch(){const u=capabilityUniverse();const appCounts={RANI_OS:u.filter(c=>c.application==='RANI_OS').length,RANI_TRADING:u.filter(c=>c.application==='RANI_TRADING').length,RANI_POOL:u.filter(c=>c.application==='RANI_POOL').length};return `<div class='apps'><button class='appbtn ${appScope==='ALL'?'active':''}' data-app='ALL'>🌐 ALL</button><button class='appbtn ${appScope==='RANI_OS'?'active':''}' data-app='RANI_OS'>🧠 RANI_OS (${appCounts.RANI_OS})</button><button class='appbtn ${appScope==='RANI_TRADING'?'active':''}' data-app='RANI_TRADING'>📈 RANI_TRADING (${appCounts.RANI_TRADING})</button><button class='appbtn ${appScope==='RANI_POOL'?'active':''}' data-app='RANI_POOL'>🏊 RANI_POOL (${appCounts.RANI_POOL})</button></div>`}
function counters(){const f=funnelData(),all=f.total,mapped=f.mapped;const items=[['funnel',`${mapped.length}/${all.length}`,'Funnel'],['blocked',f.blocked.length,'Blocked'],['owner',f.owner.length,'Owner Gates'],['missing',f.missing.length,'Missing Work'],['work',work().filter(r=>inScopeApp(appOfWork(r))).length,'Work Records'],['artifacts',artifacts.filter(a=>inScopeApp(appOfArtifact(a))).length,'Artifacts']];return `<div class='counters'>${items.map(([a,n,l])=>`<button class='counter' data-nav='${a}'><div class='num'>${esc(n)}</div><div class='label'>${esc(l)}</div></button>`).join('')}</div>`}
function layout(content){document.body.innerHTML=`<header><h1>RANI OS Admin</h1><div class='sub'>Build ${build} · Capability Funnel</div>${appSwitch()}<div class='tabs'><button data-tab='control'>Control Room</button><button data-tab='funnel'>Capability Funnel</button><button data-tab='priority'>Priority Board</button><button data-tab='capmap'>Capability Map</button><button data-tab='unmapped'>Unmapped</button><button data-tab='owner'>Owner Gates</button><button data-tab='work'>Work Records</button><button data-tab='artifacts'>Artifacts</button><button data-tab='reports'>Reports</button></div>${counters()}<div class='legend'>${chip('done','PASS / Done')} ${chip('open','Warning / Review')} ${chip('stuck','Blocked / Stop')} ${chip('other','Context / Info')}</div></header><main>${content}</main>`;wire()}
function control(){const f=funnelData(),s=state.system_status||{},c=state.current_work_item||{};return `<section><h2>Control Room</h2><div class='note'>Start from Capability Funnel. Mapping shows whether a capability is manageable, not whether it is complete.</div><div class='kpis'><div class='kpi' data-nav='funnel'><div class='num'>${f.mapped.length}/${f.total.length}</div><div>Mapped / Total</div></div><div class='kpi' data-nav='blocked'><div class='num'>${f.blocked.length}</div><div>Blocked</div></div><div class='kpi' data-nav='owner'><div class='num'>${f.owner.length}</div><div>Owner Gates</div></div><div class='kpi'><div class='num'>${build}</div><div>Build</div></div></div>${table([{K:'Source of Truth',V:s.source_of_truth},{K:'Projection Status',V:s.projection_status},{K:'Active Work',V:c.active_work_item},{K:'Scope',V:appScope}], [['Context','K'],['Value','V']])}</section>`}
function funnelView(){const f=funnelData(),total=f.total.length;const stages=[['total','Total Capabilities',f.total.length,'All capabilities in current app scope'],['mapped','Mapped',f.mapped.length,'Has explicit capability map entry'],['managed','Managed',f.managed.length,'Linked to work/artifacts/findings/bugs/candidates'],['executable','Executable',f.executable.length,'Has next safe action and no blocker'],['validated','Validated',f.validated.length,'Ready/PASS/Validated by current projection'],['approved','Approved / Closed',f.approved.length,'Done and no owner gate']];const bottlenecks=[['blocked','Blocked',f.blocked.length,'Capabilities blocked by bugs/work'],['owner','Owner Gates',f.owner.length,'Need owner decision'],['missing','Missing Work',f.missing.length,'Have missing work items'],['lowconf','Low / Medium Confidence',f.lowconf.length,'Mapping needs review']];return `<section><h2>Capability Development Funnel</h2><div class='note'>Mapping ≠ Completion. Funnel shows how capabilities evolve from known to mapped to managed to executable to validated to owner-approved.</div><h3>Funnel</h3><div class='funnel'>${stages.map(([id,label,count,desc])=>`<button class='fstage ${funnelStage===id?'active':''}' data-stage='${id}'><div>${chip(stageStatus(id,count,total),label)}</div><div class='num'>${count}/${total}</div><div class='txt'>${esc(desc)}</div></button>`).join('')}</div><h3>Bottlenecks</h3><div class='funnel'>${bottlenecks.map(([id,label,count,desc])=>`<button class='fstage ${funnelStage===id?'active':''}' data-stage='${id}'><div>${chip(stageStatus(id,count,total),label)}</div><div class='num'>${count}</div><div class='txt'>${esc(desc)}</div></button>`).join('')}</div><h3>Drill-down: ${esc(labelForStage(funnelStage))}</h3>${capTable(stageItems(funnelStage))}</section>`}
function labelForStage(s){return ({total:'Total Capabilities',mapped:'Mapped Capabilities',managed:'Managed Capabilities',executable:'Executable Capabilities',validated:'Validated Capabilities',approved:'Approved / Closed Capabilities',blocked:'Blocked Capabilities',owner:'Owner Gates',missing:'Missing Work',lowconf:'Low / Medium Confidence'})[s]||s}
function priority(){return `<section><h2>Priority Board</h2>${capTable(capModel())}</section>`}
function capmapView(){const caps=capModel();if(selected>=caps.length)selected=0;const x=caps[selected];return `<section><h2>Capability Map</h2><div class='note'>Mapped capabilities for ${appScope}. Tap a card for drill-down.</div><div class='cards'>${caps.map((x,i)=>`<div class='card ${i===selected?'active':''}' data-cap='${i}'><b>${chip(capBucket(x.c),x.c.readiness)} ${esc(x.c.name)}</b><div class='txt'>${esc(x.c.application)} · ${esc(x.c.capability_id)} · ${esc(x.c.priority)} · ${esc(x.c.mapping_confidence)}</div><div class='txt'>Missing ${x.missing.length} · Blockers ${x.blockers.length} · Gates ${x.gates.length}</div></div>`).join('')}</div>${drill(x)}</section>`}
function drill(x){if(!x)return '';return `<div class='panel'><h3>Drill-down — ${esc(x.c.name)}</h3><div class='cards'><div class='card'><b>App</b><div class='txt'>${esc(x.c.application)}</div></div><div class='card'><b>Status</b><div class='txt'>${chip(capBucket(x.c),x.c.readiness)}</div></div><div class='card'><b>Confidence</b><div class='txt'>${esc(x.c.mapping_confidence)}</div></div><div class='card'><b>Next Safe Action</b><div class='txt'>${esc(x.c.next_safe_action)}</div></div></div><div class='mini'><h3>Completion Checklist</h3>${listTable(x.check)}</div><div class='mini'><h3>Missing Work</h3>${listTable(x.missing)}</div><div class='mini'><h3>Known Work</h3>${workTable(x.known)}</div><div class='mini'><h3>Blocking Bugs</h3>${workTable(x.blockers)}</div><div class='mini'><h3>Candidate Next Work</h3>${workTable(x.cand)}</div><div class='mini'><h3>Owner Gates</h3>${listTable(x.gates)}</div><div class='mini'><h3>Related Findings</h3>${workTable(x.finds)}</div><div class='mini'><h3>Required / Related Artifacts</h3>${artifactTable(x.arts)}</div></div>`}
function unmappedView(){return `<section><h2>Unmapped Capabilities</h2>${capTable(unmappedCaps().map((c,i)=>({c:{...c,application:c.application||appOfName(c.name,c.layer),mapping_confidence:'Unmapped',next_safe_action:'Create capability-map entry'},known:[],blockers:[],cand:[],arts:[],finds:[],missing:['Create capability_id','Create completion checklist','Connect work records','Connect artifacts'],check:[],gates:[]})))}</section>`}
function owner(){let rows=[];capModel().forEach(x=>x.gates.forEach(g=>rows.push({App:esc(x.c.application),Cap:esc(x.c.name),Gate:esc(g),Status:chip('open','Owner Gate'),Next:esc(x.c.next_safe_action)})));return `<section><h2>Owner Gates</h2>${table(rows,[['App','App'],['Capability','Cap'],['Gate','Gate'],['Status','Status'],['Next','Next']])}</section>`}
function workView(){let rows=work().filter(r=>inScopeApp(appOfWork(r))).filter(r=>(workFilter.view==='all'||classify(r)===workFilter.view)&&(!workFilter.q||text(r).includes(workFilter.q.toLowerCase())));const m=metric(work().filter(r=>inScopeApp(appOfWork(r))));return `<section><h2>Work Records</h2><div class='counters'><button class='counter' data-ws='done'><div class='num'>${m.done}</div><div>✅ Done</div></button><button class='counter' data-ws='open'><div class='num'>${m.open}</div><div>⚠️ Pending</div></button><button class='counter' data-ws='stuck'><div class='num'>${m.stuck}</div><div>⛔ Stuck</div></button><button class='counter' data-ws='all'><div class='num'>${m.total}</div><div>All</div></button></div><div class='filters'><input id='wq' value='${esc(workFilter.q)}' placeholder='Search work records'><select id='wv'><option value='all'>All</option><option value='done' ${workFilter.view==='done'?'selected':''}>Done</option><option value='open' ${workFilter.view==='open'?'selected':''}>Open</option><option value='stuck' ${workFilter.view==='stuck'?'selected':''}>Stuck</option></select></div>${workTable(rows)}</section>`}
function artView(){let rows=artifacts.filter(a=>inScopeApp(appOfArtifact(a))).filter(a=>(artFilter.view==='all'||bucket(a.status)===artFilter.view)&&(!artFilter.q||text(a).includes(artFilter.q.toLowerCase())));return `<section><h2>Artifacts</h2><div class='filters'><input id='aq' value='${esc(artFilter.q)}' placeholder='Search artifacts'><select id='av'><option value='all'>All</option><option value='done' ${artFilter.view==='done'?'selected':''}>Done</option><option value='open' ${artFilter.view==='open'?'selected':''}>Open</option><option value='stuck' ${artFilter.view==='stuck'?'selected':''}>Stuck</option></select></div>${artifactTable(rows)}</section>`}
function reports(){const f=funnelData(),m=metric(work().filter(r=>inScopeApp(appOfWork(r))));const rows=[{Name:'Capability Funnel Mapped',Status:chip(stageStatus('mapped',f.mapped.length,f.total.length),`${f.mapped.length}/${f.total.length}`),Pct:pct(f.mapped.length,f.total.length),Basis:'Capability Funnel'}, {Name:'Executable',Status:chip(stageStatus('executable',f.executable.length,f.total.length),`${f.executable.length}/${f.total.length}`),Pct:pct(f.executable.length,f.total.length),Basis:'Next safe action + no blockers'}, {Name:'Blocked',Status:chip(stageStatus('blocked',f.blocked.length,f.total.length),String(f.blocked.length)),Pct:'-',Basis:'Bottleneck'}, {Name:'Work Records Done',Status:chip(m.stuck?'stuck':m.open?'open':'done',`${m.done}/${m.total}`),Pct:pct(m.done,m.total),Basis:'Work Records'}];return `<section><h2>Reports</h2>${table(rows,[['Name','Name'],['Status','Status'],['Percent','Pct'],['Basis','Basis']])}</section>`}
function view(){return tab==='funnel'||tab==='coverage'?funnelView():tab==='priority'?priority():tab==='capmap'?capmapView():tab==='unmapped'?unmappedView():tab==='owner'?owner():tab==='work'?workView():tab==='artifacts'?artView():tab==='reports'?reports():control()}
function render(){layout(view())}
function wire(){document.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>{appScope=b.dataset.app;selected=0;render()});document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab||((tab==='coverage'||tab==='funnel')&&b.dataset.tab==='funnel'));b.onclick=()=>{tab=b.dataset.tab;render()}});document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{funnelStage=b.dataset.stage;tab='funnel';render()});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(['blocked','owner','missing'].includes(n)){funnelStage=n;tab='funnel'}else if(n==='work'){workFilter={q:'',view:'all'};tab='work'}else if(n==='artifacts')tab='artifacts';else tab=n==='coverage'?'funnel':n;render()});document.querySelectorAll('[data-cap]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.cap)||0;render()});document.querySelectorAll('[data-ws]').forEach(b=>b.onclick=()=>{workFilter.view=b.dataset.ws;workFilter.q='';render()});const wq=document.getElementById('wq');if(wq)wq.oninput=e=>{workFilter.q=e.target.value;render()};const wv=document.getElementById('wv');if(wv)wv.oninput=e=>{workFilter.view=e.target.value;render()};const aq=document.getElementById('aq');if(aq)aq.oninput=e=>{artFilter.q=e.target.value;render()};const av=document.getElementById('av');if(av)av.oninput=e=>{artFilter.view=e.target.value;render()}}
async function boot(){css();const [st,mw,md,cm]=await Promise.all([fetch('state.json?b=cr015-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('managed-work.json?b=cr015-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('artifact-register-public.md?b=cr015-'+stamp,{cache:'no-store'}).then(r=>r.text()),fetch('capability-map.json?b=cr015-'+stamp,{cache:'no-store'}).then(r=>r.json())]);state=st;managed=mw;artifacts=parseArtifacts(md);capmap=cm;render()}
boot().catch(()=>{document.body.innerHTML='<section><div class="bad">Could not load CR-015 dashboard data</div></section>'});
