const build='2026-07-04-CR-013';
const stamp=Date.now();
let state={},managed={},artifacts=[],capmap={capabilities:[]},tab='control',selected=0,workFilter={q:'',view:'all'},artFilter={q:'',view:'all'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=x=>Object.values(x||{}).join(' ').toLowerCase();
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function bucket(t){t=String(t||'').toLowerCase();if(/stuck|blocked|fail|rejected|not approved|not implemented|missing|rollback/.test(t))return 'stuck';if(/pending|review|planned|deferred|in progress|candidate|not active/.test(t))return 'open';if(/pass|solved|closed|complete|verified|validated|confirmed|active|canonical|baseline/.test(t))return 'done';return 'other'}
function badge(b){return `<span class='badge ${b}'>${{done:'בוצע',open:'פתוח',stuck:'תקוע',other:'אחר'}[b]||b}</span>`}
function capBucket(c){const r=parseInt(String(c.readiness||'0').replace('%',''),10)||0;return r>=75?'done':r>=40?'open':'stuck'}
function work(){return managed.register_rows||[]}
function classify(r){return bucket(`${r.lifecycle} ${r.state}`)}
function metric(rows=work()){let done=0,open=0,stuck=0,other=0;rows.forEach(r=>{const b=classify(r);if(b==='done')done++;else if(b==='open')open++;else if(b==='stuck')stuck++;else other++});return {done,open,stuck,other,total:rows.length}}
function parseArtifacts(md){return md.split('\n').filter(l=>l.startsWith('| ')&&!l.includes('---')&&!l.includes('Artifact ID')).map(l=>{const p=l.split('|').slice(1,-1).map(x=>x.trim().replaceAll('`',''));return {id:p[0],name:p[1],location:p[2],status:p[3],domain:p[4],initiative:p[5]}}).filter(x=>x.id)}
const byId=(arr,id)=>(arr||[]).find(x=>String(x.id||'')===id);
const match=(items,terms)=>(items||[]).filter(x=>(terms||[]).some(t=>text(x).includes(String(t).toLowerCase())));
const bugs=()=>work().filter(r=>String(r.id||'').startsWith('BUG-'));
const opsbugs=()=>work().filter(r=>String(r.id||'').startsWith('OPS-BUG'));
const ideas=()=>work().filter(r=>String(r.id||'').startsWith('CAND-')||String(r.category||'').toLowerCase().includes('idea'));
function findings(){return [...(managed.not_full_backlog_warning||[]).map((r,i)=>({id:`FIND-WARN-${i+1}`,title:r.warning,category:'Finding / Warning',lifecycle:'Finding',state:r.dashboard_effect||'',source:r.repo_basis||'managed-work.json'})),...(managed.why_task_count_looked_small||[]).map((r,i)=>({id:`FIND-CAUSE-${i+1}`,title:r.reason,category:'Finding / Cause',lifecycle:'Finding',state:r.meaning||'',source:'managed-work.json'})),...(managed.next_dashboard_improvements||[]).map(r=>({id:r.id,title:r.label,category:'Finding / Improvement Candidate',lifecycle:'Future Improvement',state:r.status,source:'managed-work.json'}))]}
function capabilityUniverse(){const roadmap=(state.capabilities||[]).map(c=>({name:c.capability,source:'Capability Roadmap',readiness:c.readiness,status:c.status,layer:c.layer,priority:c.priority,next:c.next}));const mapped=(capmap.capabilities||[]).map(c=>({name:c.name,source:'Explicit Capability Map',readiness:c.readiness,status:c.status,layer:c.layer,priority:c.priority,next:c.next_safe_action,capability_id:c.capability_id}));const map=new Map();[...roadmap,...mapped].forEach(c=>{const k=norm(c.name);if(!map.has(k))map.set(k,c);else map.set(k,{...map.get(k),...c,source:'Roadmap + Explicit Map'})});return [...map.values()]}
function mappedKeys(){return new Set((capmap.capabilities||[]).map(c=>norm(c.name)))}
function unmappedCaps(){const keys=mappedKeys();return capabilityUniverse().filter(c=>!keys.has(norm(c.name)))}
function capModel(){return (capmap.capabilities||[]).map((c,i)=>{const known=(c.known_work_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const blockers=(c.blocking_bug_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const cand=(c.candidate_ids||[]).map(id=>byId(work(),id)).filter(Boolean);const arts=match(artifacts,c.artifact_queries||[]);const finds=match(findings(),c.finding_queries||[]);const gates=c.owner_gates||[];const score=(c.priority==='P0'?0:c.priority==='P1'?1:2)+(blockers.length?0:1)+(gates.length?0:1)+(c.mapping_confidence==='High'?0:1);return {i,c,known,blockers,cand,arts,finds,missing:c.missing_work||[],check:c.completion_checklist||[],gates,score}}).sort((a,b)=>a.score-b.score)}
function table(rows,cols){return `<div class='note table-count'>Records in this table: ${(rows||[]).length}</div><div class='tablewrap'><table><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${(rows||[]).map(r=>`<tr>${cols.map(c=>`<td>${r[c[1]]??''}</td>`).join('')}</tr>`).join('')||`<tr><td colspan='${cols.length}' class='bad'>No matching rows</td></tr>`}</tbody></table></div>`}
function workTable(rows){return table((rows||[]).map(r=>({State:badge(classify(r)),ID:esc(r.id),Title:esc(r.title),Category:esc(r.category),Lifecycle:esc(r.lifecycle),Status:esc(r.state)})),[['State','State'],['ID','ID'],['Title','Title'],['Category','Category'],['Lifecycle','Lifecycle'],['Status','Status']])}
function artifactTable(rows){return table((rows||[]).map(a=>({State:badge(bucket(a.status)),ID:esc(a.id),Name:esc(a.name),Status:esc(a.status),Domain:esc(a.domain)})),[['State','State'],['ID','ID'],['Name','Name'],['Status','Status'],['Domain','Domain']])}
function listTable(items){return table((items||[]).map((x,i)=>({N:i+1,Item:esc(x)})),[['#','N'],['Item','Item']])}
function css(){document.head.innerHTML=`<meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>RANI OS Admin</title><style>:root{--bg:#07111f;--card:#0d1b2e;--card2:#11243a;--text:#e8eef7;--muted:#9fb0c7;--border:#223855;--blue:#60a5fa;--green:#36d399;--yellow:#fbbf24;--red:#fb7185;--gray:#94a3b8}*{box-sizing:border-box}html,body{max-width:100%;overflow-x:hidden}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,sans-serif;line-height:1.4}header{padding:14px;background:#08162a;border-bottom:1px solid var(--border)}h1{margin:0 0 4px;font-size:22px}.sub,.note{color:var(--muted);font-size:13px}.tabs,.counters,.cards,.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px;margin-top:10px}.tabs button,.counter,.card,.kpi{padding:10px;border:1px solid var(--border);border-radius:12px;background:var(--card2);color:var(--text);cursor:pointer;text-align:left}.tabs button.active,.card.active{background:var(--blue);color:#07111f;font-weight:bold}.num{font-size:21px;font-weight:700;color:var(--blue);direction:ltr}.label,.txt{font-size:12px;color:var(--muted)}main{padding:14px;display:grid;gap:12px}section,.panel,.mini{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:14px;overflow:hidden}.tablewrap{overflow-x:hidden;border:1px solid var(--border);border-radius:12px;margin-top:8px}table{width:100%;border-collapse:collapse;direction:ltr;text-align:left;table-layout:fixed}th,td{padding:8px;border-bottom:1px solid rgba(255,255,255,.08);vertical-align:top;overflow-wrap:anywhere;word-break:break-word}th{color:var(--muted);font-weight:normal;background:#0b1a2d}.badge{display:inline-block;padding:4px 7px;border-radius:999px;font-size:11px}.badge.done{background:rgba(54,211,153,.18);color:var(--green);border:1px solid rgba(54,211,153,.5)}.badge.open{background:rgba(251,191,36,.18);color:var(--yellow);border:1px solid rgba(251,191,36,.5)}.badge.stuck{background:rgba(251,113,133,.18);color:var(--red);border:1px solid rgba(251,113,133,.5)}.badge.other{background:rgba(148,163,184,.18);color:var(--gray);border:1px solid rgba(148,163,184,.5)}.table-count{font-weight:600;color:var(--text)}.bad{color:var(--red)}.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:8px;margin:8px 0}.filters input,.filters select{width:100%;padding:10px;border-radius:10px;border:1px solid var(--border);background:var(--card2);color:var(--text)}.mini{margin-top:12px;background:rgba(255,255,255,.02)}@media(max-width:820px){header{padding:10px}h1{font-size:18px}.tabs,.counters,.cards,.kpis{grid-template-columns:1fr 1fr}main{padding:8px}section,.panel,.mini{padding:10px}table{font-size:11px}th,td{padding:6px 4px}}`}
function counters(){const all=capabilityUniverse(),mapped=capmap.capabilities||[],unmapped=unmappedCaps();const items=[['coverage',`${mapped.length}/${all.length}`,'Mapped / Total Capabilities'],['unmapped',unmapped.length,'Unmapped Capabilities'],['priority',capModel().filter(x=>x.c.priority==='P0').length,'P0 Mapped'],['capmap',mapped.length,'Mapped Capability Map'],['owner',capModel().reduce((n,x)=>n+x.gates.length,0),'Owner Gates'],['work',work().length,'Work Records'],['artifacts',artifacts.length,'Artifacts']];return `<div class='counters'>${items.map(([a,n,l])=>`<button class='counter' data-nav='${a}'><div class='num'>${esc(n)}</div><div class='label'>${esc(l)}</div></button>`).join('')}</div>`}
function layout(content){document.body.innerHTML=`<header><h1>RANI OS Admin</h1><div class='sub'>Build ${build} · Capability Mapping Coverage</div><div class='tabs'><button data-tab='control'>Control Room</button><button data-tab='coverage'>Mapping Coverage</button><button data-tab='priority'>Priority Board</button><button data-tab='capmap'>Capability Map</button><button data-tab='unmapped'>Unmapped</button><button data-tab='owner'>Owner Gates</button><button data-tab='work'>Work Records</button><button data-tab='artifacts'>Artifacts</button><button data-tab='reports'>Reports</button></div>${counters()}</header><main>${content}</main>`;wire()}
function control(){const all=capabilityUniverse(),mapped=capmap.capabilities||[],unmapped=unmappedCaps(),s=state.system_status||{},c=state.current_work_item||{};return `<section><h2>Control Room</h2><div class='note'>Capability Map now separates all capabilities from explicitly mapped capabilities.</div><div class='kpis'><div class='kpi' data-nav='coverage'><div class='num'>${mapped.length}/${all.length}</div><div>Mapped / Total Capabilities</div></div><div class='kpi' data-nav='unmapped'><div class='num'>${unmapped.length}</div><div>Unmapped Capabilities</div></div><div class='kpi' data-nav='priority'><div class='num'>${capModel().filter(x=>x.c.priority==='P0').length}</div><div>P0 Mapped Capabilities</div></div><div class='kpi' data-nav='work'><div class='num'>${work().length}</div><div>Work Records</div></div></div>${table([{K:'Source of Truth',V:s.source_of_truth},{K:'Projection Status',V:s.projection_status},{K:'Active Work',V:c.active_work_item},{K:'Build',V:build}], [['Field','K'],['Value','V']])}</section>`}
function coverage(){const all=capabilityUniverse(),mapped=capmap.capabilities||[],unmapped=unmappedCaps();const summary=[{Metric:'Total Capability Universe',Value:all.length,Meaning:'Roadmap capabilities plus explicit mapped capabilities'}, {Metric:'Explicitly Mapped Capabilities',Value:mapped.length,Meaning:'Capabilities with capability_id, checklist, missing work and gates'}, {Metric:'Unmapped Capabilities',Value:unmapped.length,Meaning:'Need capability-map entry before reliable drill-down'}, {Metric:'Coverage',Value:`${Math.round(mapped.length*100/(all.length||1))}%`,Meaning:'Mapped / Total'}];return `<section><h2>Mapping Coverage</h2><div class='note'>This explains why only part of the capability universe has full drill-down.</div>${table(summary,[['Metric','Metric'],['Value','Value'],['Meaning','Meaning']])}<h3>Mapping Backlog</h3>${unmappedTable()}</section>`}
function unmappedTable(){return table(unmappedCaps().map(c=>({Capability:esc(c.name),Layer:esc(c.layer||''),Status:esc(c.status||''),Readiness:esc(c.readiness||''),Missing:'capability_id / known_work_ids / checklist / owner_gates',Next:'Create capability-map entry'})),[['Capability','Capability'],['Layer','Layer'],['Status','Status'],['Readiness','Readiness'],['Missing Mapping','Missing'],['Next','Next']])}
function priority(){return `<section><h2>Priority Board</h2>${table(capModel().map(x=>({P:esc(x.c.priority),Cap:esc(x.c.name),Ready:esc(x.c.readiness),Conf:esc(x.c.mapping_confidence),Block:String(x.blockers.length),Gates:String(x.gates.length),Missing:String(x.missing.length),Next:esc(x.c.next_safe_action)})),[['Priority','P'],['Capability','Cap'],['Readiness','Ready'],['Confidence','Conf'],['Blockers','Block'],['Owner Gates','Gates'],['Missing','Missing'],['Next','Next']])}</section>`}
function capmapView(){const caps=capModel();if(selected>=caps.length)selected=0;const x=caps[selected];return `<section><h2>Capability Map — mapped capabilities only</h2><div class='note'>Showing ${caps.length} explicitly mapped capabilities out of ${capabilityUniverse().length} total capabilities.</div><div class='cards'>${caps.map((x,i)=>`<div class='card ${i===selected?'active':''}' data-cap='${i}'><b>${esc(x.c.name)}</b><div class='txt'>${esc(x.c.capability_id)} · ${esc(x.c.priority)} · ${esc(x.c.readiness)} · ${esc(x.c.mapping_confidence)}</div><div class='txt'>Missing ${x.missing.length} · Blockers ${x.blockers.length} · Gates ${x.gates.length}</div></div>`).join('')}</div>${drill(x)}</section>`}
function drill(x){if(!x)return '';return `<div class='panel'><h3>Drill-down — ${esc(x.c.name)}</h3><div class='cards'><div class='card'><b>Capability ID</b><div class='txt'>${esc(x.c.capability_id)}</div></div><div class='card'><b>Confidence</b><div class='txt'>${esc(x.c.mapping_confidence)}</div></div><div class='card'><b>Readiness</b><div class='txt'>${esc(x.c.readiness)}</div></div><div class='card'><b>Next Safe Action</b><div class='txt'>${esc(x.c.next_safe_action)}</div></div></div><div class='mini'><h3>Completion Checklist</h3>${listTable(x.check)}</div><div class='mini'><h3>Missing Work</h3>${listTable(x.missing)}</div><div class='mini'><h3>Known Work</h3>${workTable(x.known)}</div><div class='mini'><h3>Blocking Bugs</h3>${workTable(x.blockers)}</div><div class='mini'><h3>Candidate Next Work</h3>${workTable(x.cand)}</div><div class='mini'><h3>Owner Gates</h3>${listTable(x.gates)}</div><div class='mini'><h3>Related Findings</h3>${workTable(x.finds)}</div><div class='mini'><h3>Required / Related Artifacts</h3>${artifactTable(x.arts)}</div></div>`}
function owner(){let rows=[];capModel().forEach(x=>x.gates.forEach(g=>rows.push({Cap:esc(x.c.name),Gate:esc(g),Next:esc(x.c.next_safe_action),Conf:esc(x.c.mapping_confidence)})));return `<section><h2>Owner Gates</h2>${table(rows,[['Capability','Cap'],['Gate','Gate'],['Next','Next'],['Confidence','Conf']])}</section>`}
function workView(){let rows=work().filter(r=>(workFilter.view==='all'||classify(r)===workFilter.view)&&(!workFilter.q||text(r).includes(workFilter.q.toLowerCase())));const m=metric(work());return `<section><h2>Work Records</h2><div class='counters'><button class='counter' data-ws='done'><div class='num'>${m.done}</div><div>Done</div></button><button class='counter' data-ws='open'><div class='num'>${m.open}</div><div>Pending</div></button><button class='counter' data-ws='stuck'><div class='num'>${m.stuck}</div><div>Stuck</div></button><button class='counter' data-ws='all'><div class='num'>${m.total}</div><div>All</div></button></div><div class='filters'><input id='wq' value='${esc(workFilter.q)}' placeholder='Search work records'><select id='wv'><option value='all'>All</option><option value='done' ${workFilter.view==='done'?'selected':''}>Done</option><option value='open' ${workFilter.view==='open'?'selected':''}>Open</option><option value='stuck' ${workFilter.view==='stuck'?'selected':''}>Stuck</option></select></div>${workTable(rows)}</section>`}
function artView(){let rows=artifacts.filter(a=>(artFilter.view==='all'||bucket(a.status)===artFilter.view)&&(!artFilter.q||text(a).includes(artFilter.q.toLowerCase())));return `<section><h2>Artifacts</h2><div class='filters'><input id='aq' value='${esc(artFilter.q)}' placeholder='Search artifacts'><select id='av'><option value='all'>All</option><option value='done' ${artFilter.view==='done'?'selected':''}>Done</option><option value='open' ${artFilter.view==='open'?'selected':''}>Open</option><option value='stuck' ${artFilter.view==='stuck'?'selected':''}>Stuck</option></select></div>${artifactTable(rows)}</section>`}
function reports(){const all=capabilityUniverse(),mapped=capmap.capabilities||[],m=metric(work());const rows=[{Name:'Capability Mapping Coverage',Done:`${mapped.length}/${all.length}`,Pct:`${Math.round(mapped.length*100/(all.length||1))}%`,Open:all.length-mapped.length,Basis:'capability-map.json vs roadmap'}, {Name:'Work Records status',Done:`${m.done}/${m.total}`,Pct:`${Math.round(m.done*100/(m.total||1))}%`,Open:m.open,Basis:'Work Records'}];return `<section><h2>Reports</h2>${table(rows,[['Name','Name'],['Done / Total','Done'],['Percent','Pct'],['Open','Open'],['Basis','Basis']])}</section>`}
function listTable(items){return table((items||[]).map((x,i)=>({N:i+1,Item:esc(x)})),[['#','N'],['Item','Item']])}
function view(){return tab==='coverage'?coverage():tab==='priority'?priority():tab==='capmap'?capmapView():tab==='unmapped'?`<section><h2>Unmapped Capabilities</h2>${unmappedTable()}</section>`:tab==='owner'?owner():tab==='work'?workView():tab==='artifacts'?artView():tab==='reports'?reports():control()}
function render(){layout(view())}
function wire(){document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.onclick=()=>{tab=b.dataset.tab;render()}});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='bugs'){workFilter.q='BUG';tab='work'}else if(n==='ideas'){workFilter.q='CAND';tab='work'}else if(n==='work'){workFilter={q:'',view:'all'};tab='work'}else if(n==='artifacts')tab='artifacts';else tab=n;render()});document.querySelectorAll('[data-cap]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.cap)||0;render()});document.querySelectorAll('[data-ws]').forEach(b=>b.onclick=()=>{workFilter.view=b.dataset.ws;workFilter.q='';render()});const wq=document.getElementById('wq');if(wq)wq.oninput=e=>{workFilter.q=e.target.value;render()};const wv=document.getElementById('wv');if(wv)wv.oninput=e=>{workFilter.view=e.target.value;render()};const aq=document.getElementById('aq');if(aq)aq.oninput=e=>{artFilter.q=e.target.value;render()};const av=document.getElementById('av');if(av)av.oninput=e=>{artFilter.view=e.target.value;render()}}
function layout(content){document.body.innerHTML=`<header><h1>RANI OS Admin</h1><div class='sub'>Build ${build} · Mapping Coverage</div><div class='tabs'><button data-tab='control'>Control Room</button><button data-tab='coverage'>Mapping Coverage</button><button data-tab='priority'>Priority Board</button><button data-tab='capmap'>Capability Map</button><button data-tab='unmapped'>Unmapped</button><button data-tab='owner'>Owner Gates</button><button data-tab='work'>Work Records</button><button data-tab='artifacts'>Artifacts</button><button data-tab='reports'>Reports</button></div>${counters()}</header><main>${content}</main>`;wire()}
async function boot(){css();const [st,mw,md,cm]=await Promise.all([fetch('state.json?b=cr013-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('managed-work.json?b=cr013-'+stamp,{cache:'no-store'}).then(r=>r.json()),fetch('artifact-register-public.md?b=cr013-'+stamp,{cache:'no-store'}).then(r=>r.text()),fetch('capability-map.json?b=cr013-'+stamp,{cache:'no-store'}).then(r=>r.json())]);state=st;managed=mw;artifacts=parseArtifacts(md);capmap=cm;render()}
boot().catch(()=>{document.body.innerHTML='<section><div class="bad">Could not load CR-013 dashboard data</div></section>'});
